services:
  tor-relay:
    image: tor-relay:latest
    container_name: tor
    user: "100:101"
    ports:
      - 9001:9001
      - 9030:9030
    volumes:
      - ./data:/var/lib/tor
    restart: always
